# Generated by Django 4.2.19 on 2025-03-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskFlow', '0004_grupo_rol_notificacion_mensaje_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='TaskFlow.proyecto'),
        ),
    ]
